server:
  port: ${PORT:8762}

eureka:
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}


spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: portfolio-tracker-client
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI:https://keycloak-production-c9a0.up.railway.app/realms/PortfolioTrackerApp}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:https://keycloak-production-c9a0.up.railway.app/realms/PortfolioTrackerApp}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: test-public
          uri: lb://TEST
          predicates:
            - Path=/api/v1/public/**
        - id: test-private
          uri: lb://TEST
          predicates:
            - Path=/api/v1/private/**
        - id: test-logout
          uri: lb://TEST
          predicates:
            - Path=/api/v1/logout
        - id: eureka
          uri: lb://EUREKA
          predicates:
            - Path=/eureka/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors: ## CORS Configuration
        cors-configurations:
          '[/**]':
            allowedOrigins: ${ALLOWED_ORIGINS:*}
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH

## We enable the Actuator API to be able to access <<host>>/actuator/gateway/routes
## We expose the routings that have been automatically detected (all)
## Depending on the ROUTE_TABLES_ENABLED environment variable (true by default)
management:
  endpoint:
    gateway:
      enabled: ${ROUTE_TABLES_ENABLED:true}
  endpoints:
    web:
      exposure:
        include:
          - '*'