server:
  port: ${PORT:8762}

eureka:
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}


spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: login-app
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI:https://keycloak-production-c9a0.up.railway.app/realms/PortfolioTrackerApp}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:https://keycloak-production-c9a0.up.railway.app/realms/PortfolioTrackerApp}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: test-public
          uri: lb:http://PORTFOLIO-TRACKER-BACKEND
          predicates:
            - Path=/api/v1/test/public
        - id: test-private
          uri: lb:http://PORTFOLIO-TRACKER-BACKEND
          predicates:
            - Path=/api/v1/test/private
        - id: eureka
          uri: lb:http://EUREKA
          predicates:
            - Path=/eureka/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
